### PR TITLE
Remove feed format

### LINKED ISSUE #8: Id format
Similar to the [fusion identities](https://github.com/ssb-ngi-pointer/fusion-identity-spec) should we encode meta feeds identifiers in a special way? It might make it easier to reason about different feed types.

### PR DESCRIPTION
**Pull request by arj03**
@cryptix this PR removes `feedformat` from content as that can be deduces from the feed id. Fixes the examples to make that more clear and fixes the nonce to be 32 bytes. I'll get a confirmation on that after my call in about an hour.

Fixes #8

### CODE REVIEW

**Comment by cryptix** [comment]
will followup with updated vectors once we know what's what.

**Comment by arj03** [comment]
@cryptix this should be ready now. Added meeting notes and a salt value :)

**Comment by arj03** [comment]
This should also fix #12. The public part was actually suggested by keks, so should be fine.

**Comment by arj03** [comment]
Also this should fix #10

**Comment by cryptix** [comment]
Great

**Pull request merged**
